testng_hw
buykoam/AQA21 pull request #2
Opened 2023-06-26 19:13 UTC by buykoam

2023-07-08 19:02 UTC, wildpioneer requested changes

2023-07-08 19:02 UTC, wildpioneer commented on src/test/java/HWTest.java
>      @Test (groups = "smoke")
1. Форматирование - методы разделяются пустой строкой
2. Отсутствуют тесты на: 
@Parameters
retryAnalyzer
Double.NaN
Double.NEGATIVE_INFINITY
Double.POSITIVE_INFINITY

2023-07-23 13:12 UTC, wildpioneer commented
Планируешь ли ты исправить замечания?

2023-07-23 13:34 UTC, buykoam commented on src/test/java/HWTest.java
>      @Test (groups = "smoke")
Планирую провести работу над ошибками к след. выходным

2023-07-31 15:58 UTC, buykoam commented on src/test/java/HWTest.java
>      @Test (groups = "smoke")
Внесла изменения

2023-08-02 08:47 UTC, wildpioneer commented
Проверено

2023-08-02 08:47 UTC, closed without merging