add files
buykoam/AQA21 pull request #6
Opened 2023-07-23 18:52 UTC by buykoam

2023-08-02 08:47 UTC, wildpioneer requested changes

2023-08-02 08:47 UTC, wildpioneer commented on src/test/java/tests/FileUploadHWTest.java
> +        String pathToFile = FileUploadHWTest.class.getClassLoader().getResource(" D:\\TeachMeAQA\\AQA21onl-testng\\src\\test\\resources\\download.jpeg").getPath();
У меня нет такого пути

2023-08-09 03:52 UTC, buykoam commented on src/test/java/tests/FileUploadHWTest.java
> +        String pathToFile = FileUploadHWTest.class.getClassLoader().getResource(" D:\\TeachMeAQA\\AQA21onl-testng\\src\\test\\resources\\download.jpeg").getPath();
Если прописываю getResource("download.jpeg").getPath(); то у меня возникает ошибка: File not found : /D:/TeachMeAQA/AQA21onl-testng/target/test-classes/download.jpeg . Не могу понять почему именно там ищет файл и не находит, если актуальный путь D:\\TeachMeAQA\\AQA21onl-testng\\src\\test\\resources\\download.jpeg"

2023-08-28 11:23 UTC, wildpioneer commented
Проверено

2023-08-28 11:23 UTC, closed without merging