Task #12 Wrappers
buykoam/AQA21 pull request #8
Opened 2023-08-05 19:21 UTC by buykoam

2023-08-07 15:42 UTC, wildpioneer requested changes

2023-08-07 15:42 UTC, wildpioneer commented on src/test/java/elements/CheckBox.java
> +        if (uiElement.isSelected() && !uiElement.isSelected()) {
Отличное решение. Только маленькое замечание - строки 18 и 19 идентичны 23 и 24 - а следовательно это дубликат кода - и нужно просто вынести в отдельный метод

2023-08-07 15:42 UTC, wildpioneer commented on src/test/java/elements/DropDown.java
> +        uiElement.click();
Данный метод только нажимает dropdown. Однако я не вижу здесь методов для выбора значения и фильтрации

2023-08-07 15:42 UTC, wildpioneer commented on src/test/java/elements/RadioButton.java
> +        uiElement.click();
Аналогично как и для dropdown

2023-08-20 09:08 UTC, buykoam commented on src/test/java/elements/RadioButton.java
> +        uiElement.click();
Переделала

2023-08-28 11:23 UTC, wildpioneer commented
Проверено

2023-08-28 11:23 UTC, closed without merging